version: '3.9'


services:
  csgo_app:     
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - csgo_postgres
      - csgo_clickhouse        

  csgo_postgres:    
    image: postgres:15.6-bullseye
    container_name: csgo_postgres
    hostname: csgo_postgres
    environment:
      - POSTGRES_USER=csgo_user
      - POSTGRES_PASSWORD=csgo_password
      - POSTGRES_DB=csgo_database
      - POSTGRES_INITDB_ARGS='--encoding=UTF-8'
    ports:
      -  5432:5432
    volumes:
      - csgo_postgres:/var/lib/postgresql/data
    

  csgo_clickhouse:
    image: clickhouse/clickhouse-server:23.12.4.15-alpine    
    container_name: csgo_clickhouse
    hostname: csgo_clickhouse
    environment:
      - CLICKHOUSE_USER=csgo_user
      - CLICKHOUSE_PASSWORD=csgo_password
      - CLICKHOUSE_DB=csgo_database
    volumes:
      - csgo_clickhouse:/var/lib/clickhouse
    ports:
      - '9000:9000'
      - '8123:8123'
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144    
    restart: unless-stopped


volumes:
  csgo_postgres:
  csgo_clickhouse: